version: "3"

services:
  api:
    image: slack-bot-socket-server:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slack-bot-socket-server
    # ? Dockerfileの方で指定しているから -b 9001 app.main:app は不要？
    command: "--preload --log-level debug -b 0.0.0.0:9001 app.main:app"
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      FLASK_DEBUG: "False"
    ports:
      - 3000:3000
      # ? 3000:9001の間違い？
    networks:
      - api
    secrets:
      # /run/secrets/my_secret/credential.json
      - my_secret

secrets:
  my_secret:
    file: ~/.secrets/credential.json
